### ISSUE TITLE
Xoom-Designer Generation Failure

### ISSUE THREAD

**Issue by gollen833** [vlingo/xoom-designer#134]
**Action**: Project Generation <br> **OS**:  Windows 10 <br> **Java Version**:  1.8.0_312 <br>**Designer Version**: 1.8.9-SNAPSHOT <br> **Target**: filesystem <br> **Error Type**: CODEGEN_FAILURE <br>**Designer Model**: <br><pre> {<br>  "context": {<br>    "groupId": "com.archforce",<br>    "artifactId": "order-taking",<br>    "artifactVersion": "1.0.0",<br>    "packageName": "com.archforce.ordertaking"<br>  },<br>  "model": {<br>    "persistenceSettings": {<br>      "storageType": "JOURNAL",<br>      "useCQRS": true,<br>      "projections": "EVENT_BASED",<br>      "database": "IN_MEMORY",<br>      "commandModelDatabase": "MYSQL",<br>      "queryModelDatabase": "MYSQL"<br>    },<br>    "aggregateSettings": [<br>      {<br>        "api": {<br>          "rootPath": "/orders",<br>          "routes": []<br>        },<br>        "aggregateName": "Order",<br>        "stateFields": [<br>          {<br>            "name": "id",<br>            "type": "String"<br>          }<br>        ],<br>        "methods": [<br>          {<br>            "name": "accept",<br>            "parameters": [],<br>            "useFactory": true,<br>            "event": "OrderCreated"<br>          },<br>          {<br>            "name": "validate",<br>            "parameters": [],<br>            "useFactory": false<br>          },<br>          {<br>            "name": "price",<br>            "parameters": [],<br>            "useFactory": false<br>          }<br>        ],<br>        "events": [<br>          {<br>            "name": "OrderCreated",<br>            "fields": [<br>              "id"<br>            ]<br>          },<br>          {<br>            "name": "OrderValidated",<br>            "fields": [<br>              "id"<br>            ]<br>          },<br>          {<br>            "name": "OrderPriced",<br>            "fields": [<br>              "id"<br>            ]<br>          }<br>        ],<br>        "consumerExchange": {<br>          "receivers": []<br>        },<br>        "producerExchange": {<br>          "schemaGroup": "",<br>          "outgoingEvents": []<br>        }<br>      }<br>    ],<br>    "valueObjectSettings": [<br>      {<br>        "name": "UnvalidatedCustomerInfo",<br>        "fields": [<br>          {<br>            "name": "firstName",<br>            "type": "String",<br>            "collectionType": ""<br>          },<br>          {<br>            "name": "lastName",<br>            "type": "String",<br>            "collectionType": ""<br>          },<br>          {<br>            "name": "emailAddress",<br>            "type": "String",<br>            "collectionType": ""<br>          }<br>        ]<br>      },<br>      {<br>        "name": "UnvalidatedAddress",<br>        "fields": [<br>          {<br>            "name": "addressLine1",<br>            "type": "String",<br>            "collectionType": ""<br>          },<br>          {<br>            "name": "addressLine2",<br>            "type": "String",<br>            "collectionType": ""<br>          },<br>          {<br>            "name": "addressLine3",<br>            "type": "String",<br>            "collectionType": ""<br>          },<br>          {<br>            "name": "addressLine4",<br>            "type": "String",<br>            "collectionType": ""<br>          },<br>          {<br>            "name": "city",<br>            "type": "String",<br>            "collectionType": ""<br>          },<br>          {<br>            "name": "zipCode",<br>            "type": "String",<br>            "collectionType": ""<br>          }<br>        ]<br>      },<br>      {<br>        "name": "UnvalidatedOrderLine",<br>        "fields": [<br>          {<br>            "name": "orderLineId",<br>            "type": "String",<br>            "collectionType": ""<br>          },<br>          {<br>            "name": "productCode",<br>            "type": "String",<br>            "collectionType": ""<br>          },<br>          {<br>            "name": "quantity",<br>            "type": "float",<br>            "collectionType": ""<br>          }<br>        ]<br>      }<br>    ]<br>  },<br>  "deployment": {<br>    "type": "NONE",<br>    "dockerImage": "",<br>    "kubernetesImage": "",<br>    "kubernetesPod": "",<br>    "clusterTotalNodes": 3,<br>    "clusterPort": 50011,<br>    "producerExchangePort": 19762,<br>    "httpServerPort": 8081,<br>    "pullSchemas": false<br>  },<br>  "schemata": {<br>    "host": "localhost",<br>    "port": 9019<br>  },<br>  "projectDirectory": "C:\\Users\\luogl\\VLINGO-XOOM\\com.archforce\\order-taking1",<br>  "useAnnotations": true,<br>  "useAutoDispatch": true,<br>  "generateUIWith": "ReactJS",<br>  "generateUI": false<br>} </pre><br> **Stacktrace**: <br><pre>java.lang.NullPointerException
	at io.vlingo.xoom.designer.codegen.java.model.aggregate.EventHandler.equals(EventHandler.java:43)
	at java.util.HashMap.getNode(HashMap.java:580)
	at java.util.HashMap.containsKey(HashMap.java:597)
	at java.util.HashSet.contains(HashSet.java:204)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:173)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.vlingo.xoom.designer.codegen.java.model.aggregate.EventHandler.from(EventHandler.java:28)
	at io.vlingo.xoom.designer.codegen.java.model.aggregate.AggregateTemplateData.<init>(AggregateTemplateData.java:50)
	at io.vlingo.xoom.designer.codegen.java.model.ModelTemplateDataFactory.loadTemplates(ModelTemplateDataFactory.java:54)
	at io.vlingo.xoom.designer.codegen.java.model.ModelTemplateDataFactory.lambda$from$0(ModelTemplateDataFactory.java:40)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:269)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.vlingo.xoom.designer.codegen.java.model.ModelTemplateDataFactory.from(ModelTemplateDataFactory.java:41)
	at io.vlingo.xoom.designer.codegen.java.model.ModelGenerationStep.buildTemplatesData(ModelGenerationStep.java:21)
	at io.vlingo.xoom.codegen.template.TemplateProcessingStep.process(TemplateProcessingStep.java:22)
	at io.vlingo.xoom.designer.ModelProcessingManager.lambda$processSteps$3(ModelProcessingManager.java:67)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at io.vlingo.xoom.designer.ModelProcessingManager.processSteps(ModelProcessingManager.java:67)
	at io.vlingo.xoom.designer.ModelProcessingManager.lambda$generate$1(ModelProcessingManager.java:36)
	at io.vlingo.xoom.common.completes.FutureCompletes$State.lambda$functionWrapper$8(FutureCompletes.java:576)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:943)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
</pre>

**Comment by VaughnVernon** [comment]
Thanks for reporting, @gollen833. It appears that currently the codegen expects all declared events to be used/applied by at least one command method. We are fixing this but to quickly work around the issue you can define two additional methods and map each method to one of the other two events.

**Comment by VaughnVernon** [comment]
Fixed by https://github.com/vlingo/xoom-designer/pull/135

@gollen833 The fix is available in the latest 1.9.2-SNAPSHOT. We will release 1.9.3 soon.
