### ISSUE TITLE
io.vlingo.xoom.cli.UnknownCommandException

### ISSUE THREAD

**Issue by superfrankiefan** [vlingo/xoom-designer#160]
Dear teams,
When startup xoom designer using cli, it raises UnknownCommandException as fowllowing:
```
Exception in thread "main" io.vlingo.xoom.cli.UnknownCommandException: The informed command is not supported --currentDirectory /Users/xxx/Desktop/xxx/xxx/DDD/designer
	at io.vlingo.xoom.cli.task.Task.lambda$triggeredBy$1(Task.java:44)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.vlingo.xoom.cli.task.Task.triggeredBy(Task.java:44)
	at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.main(CommandLineInterfaceInitializer.java:26)
```
Is there any limitation about the '--currentDirectory' args?

Thanks & Regards,
Frankie

**Comment by superfrankiefan** [comment]
> @superfrankiefan how did you attempt to start xoom designer?
Hi @jakzal, I used the CLI "./xoom gui" & "./xoom designer" to start designer. I have set the ENV VLINGO_XOOM_DESIGNER_HOME to the installation path. The error as following:
`❯ ./xoom gui
=========================
service: xoom-designer.
=========================
23:15:51.353 [main] ERROR io.vlingo.xoom.actors.Logger - java.lang.NullPointerException
io.vlingo.xoom.designer.DesignerServerInitializationException: java.lang.NullPointerException
	at io.vlingo.xoom.designer.DesignerInitializer.startServer(DesignerInitializer.java:62)
	at io.vlingo.xoom.designer.DesignerInitializer.start(DesignerInitializer.java:32)
	at io.vlingo.xoom.cli.task.designer.DesignerTask.run(DesignerTask.java:30)
	at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.runTask(CommandLineInterfaceInitializer.java:32)
	at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.main(CommandLineInterfaceInitializer.java:26)
Caused by: java.lang.NullPointerException: null
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:506)
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:107)
	at io.vlingo.xoom.cluster.model.application.ClusterApplication.instance(ClusterApplication.java:29)
	at io.vlingo.xoom.cluster.model.ClusterControl.instance(ClusterControl.java:40)
	at io.vlingo.xoom.cluster.model.ClusterControl.instance(ClusterControl.java:26)
	at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:47)
	at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:33)
	at io.vlingo.xoom.lattice.grid.GridNodeBootstrap.boot(GridNodeBootstrap.java:30)
	at io.vlingo.xoom.lattice.grid.Grid.<init>(Grid.java:101)
	at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:74)
	at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:65)
	at io.vlingo.xoom.turbo.Boot.start(Boot.java:55)
	at io.vlingo.xoom.designer.XoomInitializer.<init>(XoomInitializer.java:38)
	at io.vlingo.xoom.designer.XoomInitializer.main(XoomInitializer.java:87)
	at io.vlingo.xoom.designer.DesignerInitializer.startServer(DesignerInitializer.java:60)
	... 4 common frames omitted
Exception in thread "main" io.vlingo.xoom.designer.DesignerServerInitializationException: java.lang.NullPointerException
	at io.vlingo.xoom.designer.DesignerInitializer.startServer(DesignerInitializer.java:62)
	at io.vlingo.xoom.designer.DesignerInitializer.start(DesignerInitializer.java:32)
	at io.vlingo.xoom.cli.task.designer.DesignerTask.run(DesignerTask.java:30)
	at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.runTask(CommandLineInterfaceInitializer.java:32)
	at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.main(CommandLineInterfaceInitializer.java:26)
Caused by: java.lang.NullPointerException
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:506)
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:107)
	at io.vlingo.xoom.cluster.model.application.ClusterApplication.instance(ClusterApplication.java:29)
	at io.vlingo.xoom.cluster.model.ClusterControl.instance(ClusterControl.java:40)
	at io.vlingo.xoom.cluster.model.ClusterControl.instance(ClusterControl.java:26)
	at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:47)
	at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:33)
	at io.vlingo.xoom.lattice.grid.GridNodeBootstrap.boot(GridNodeBootstrap.java:30)
	at io.vlingo.xoom.lattice.grid.Grid.<init>(Grid.java:101)23:15:51.353 [pool-2-thread-1] ERROR io.vlingo.xoom.actors.Logger - XOOM: FAILED: Actor proxy io.vlingo.xoom.lattice.util.HardRefHolder not created for main or test: Actor proxy io.vlingo.xoom.lattice.util.HardRefHolder not created because: null
java.lang.IllegalArgumentException: Actor proxy io.vlingo.xoom.lattice.util.HardRefHolder not created for main or test: Actor proxy io.vlingo.xoom.lattice.util.HardRefHolder not created because: null
	at io.vlingo.xoom.actors.ActorProxy.tryGenerateCreate(ActorProxy.java:101)
	at io.vlingo.xoom.actors.ActorProxy.createFor(ActorProxy.java:38)
	at io.vlingo.xoom.actors.Stage.actorProxyFor(Stage.java:599)
	at io.vlingo.xoom.actors.Stage.actorProtocolFor(Stage.java:548)
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:505)
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:107)
	at io.vlingo.xoom.actors.World.actorFor(World.java:152)
	at io.vlingo.xoom.lattice.grid.GridNode.<init>(GridNode.java:67)
	at io.vlingo.xoom.lattice.grid.GridNodeBootstrap$GridNodeInstantiator.instantiate(GridNodeBootstrap.java:75)
	at io.vlingo.xoom.lattice.grid.GridNodeBootstrap$GridNodeInstantiator.instantiate(GridNodeBootstrap.java:61)
	at io.vlingo.xoom.actors.ActorFactory.actorFor(ActorFactory.java:71)
	at io.vlingo.xoom.actors.Stage.createRawActor(Stage.java:838)
	at io.vlingo.xoom.actors.Stage.actorProtocolFor(Stage.java:547)
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:505)
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:107)
	at io.vlingo.xoom.cluster.model.application.ClusterApplication.instance(ClusterApplication.java:29)
	at io.vlingo.xoom.cluster.model.ClusterControl.instance(ClusterControl.java:40)
	at io.vlingo.xoom.cluster.model.ClusterControl.instance(ClusterControl.java:26)
	at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:47)
	at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:33)
	at io.vlingo.xoom.lattice.grid.GridNodeBootstrap.boot(GridNodeBootstrap.java:30)
	at io.vlingo.xoom.lattice.grid.Grid.<init>(Grid.java:101)
	at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:74)
	at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:65)
	at io.vlingo.xoom.turbo.Boot.start(Boot.java:55)
	at io.vlingo.xoom.designer.XoomInitializer.<init>(XoomInitializer.java:38)
	at io.vlingo.xoom.designer.XoomInitializer.main(XoomInitializer.java:87)
	at io.vlingo.xoom.designer.DesignerInitializer.startServer(DesignerInitializer.java:60)
	at io.vlingo.xoom.designer.DesignerInitializer.start(DesignerInitializer.java:32)
	at io.vlingo.xoom.cli.task.designer.DesignerTask.run(DesignerTask.java:30)
	at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.runTask(CommandLineInterfaceInitializer.java:32)
	at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.main(CommandLineInterfaceInitializer.java:26)
Caused by: java.lang.IllegalArgumentException: Actor proxy io.vlingo.xoom.lattice.util.HardRefHolder not created because: null
	at io.vlingo.xoom.actors.ActorProxy.tryGenerateCreate(ActorProx
y.java:118)
	at io.vlingo.xoom.actors.ActorProxy.tryGenerateCreate(ActorProxy.java:98)
	... 31 common frames omitted
Caused by: java.lang.NullPointerException: null
	at io.vlingo.xoom.common.compiler.DynaCompiler.compile(DynaCompiler.java:62)
	at io.vlingo.xoom.actors.ActorProxy.tryGenerateCreate(ActorProxy.java:115)
	... 32 common frames omitted
	at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:74)
	at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:65)
	at io.vlingo.xoom.turbo.Boot.start(Boot.java:55)
	at io.vlingo.xoom.designer.XoomInitializer.<init>(XoomInitializer.java:38)
	at io.vlingo.xoom.designer.XoomInitializer.main(XoomInitializer.java:87)
	at io.vlingo.xoom.designer.DesignerInitializer.startServer(DesignerInitializer.java:60)
	... 4 more
23:15:51.358 [pool-2-thread-2] ERROR io.vlingo.xoom.actors.Logger - Actor instantiation failed because: null
java.lang.NullPointerException: null
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:506)
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:107)
	at io.vlingo.xoom.actors.World.actorFor(World.java:152)
	at io.vlingo.xoom.lattice.grid.GridNode.<init>(GridNode.java:67)
	at io.vlingo.xoom.lattice.grid.GridNodeBootstrap$GridNodeInstantiator.instantiate(GridNodeBootstrap.java:75)
	at io.vlingo.xoom.lattice.grid.GridNodeBootstrap$GridNodeInstantiator.instantiate(GridNodeBootstrap.java:61)
	at io.vlingo.xoom.actors.ActorFactory.actorFor(ActorFactory.java:71)
	at io.vlingo.xoom.actors.Stage.createRawActor(Stage.java:838)
	at io.vlingo.xoom.actors.Stage.actorProtocolFor(Stage.java:547)
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:505)
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:107)
	at io.vlingo.xoom.cluster.model.application.ClusterApplication.instance(ClusterApplication.java:29)
	at io.vlingo.xoom.cluster.model.ClusterControl.instance(ClusterControl.java:40)
	at io.vlingo.xoom.cluster.model.ClusterControl.instance(ClusterControl.java:26)
	at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:47)
	at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:33)
	at io.vlingo.xoom.lattice.grid.GridNodeBootstrap.boot(GridNodeBootstrap.java:30)
	at io.vlingo.xoom.lattice.grid.Grid.<init>(Grid.java:101)
	at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:74)
	at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:65)
	at io.vlingo.xoom.turbo.Boot.start(Boot.java:55)
	at io.vlingo.xoom.designer.XoomInitializer.<init>(XoomInitializer.java:38)
	at io.vlingo.xoom.designer.XoomInitializer.main(XoomInitializer.java:87)
	at io.vlingo.xoom.designer.DesignerInitializer.startServer(DesignerInitializer.java:60)
	at io.vlingo.xoom.designer.DesignerInitializer.start(DesignerInitializer.java:32)
	at io.vlingo.xoom.cli.task.designer.DesignerTask.run(DesignerTask.java:30)
	at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.runTask(CommandLineInterfaceInitializer.java:32)
	at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.main(CommandLineInterfaceInitializer.java:26)
23:15:51.359 [pool-2-thread-2] ERROR io.vlingo.xoom.actors.Logger - XOOM: FAILED: Actor instantiation failed because: null
java.lang.IllegalArgumentException: Actor instantiation failed because: null
	at io.vlingo.xoom.actors.Stage.createRawActor(Stage.java:841)
	at io.vlingo.xoom.actors.Stage.actorProtocolFor(Stage.java:547)
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:505)
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:107)
	at io.vlingo.xoom.cluster.model.application.ClusterApplication.instance(ClusterApplication.java:29)
	at io.vlingo.xoom.cluster.model.ClusterControl.instance(ClusterControl.java:40)
	at io.vlingo.xoom.cluster.model.ClusterControl.instance(ClusterControl.java:26)
	at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:47)
	at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:33)
	at io.vlingo.xoom.lattice.grid.GridNodeBootstrap.boot(GridNodeBootstrap.java:30)
	at io.vlingo.xoom.lattice.grid.Grid.<init>(Grid.java:101)
	at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:74)
	at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:65)
	at io.vlingo.xoom.turbo.Boot.start(Boot.java:55)
	at io.vlingo.xoom.designer.XoomInitializer.<init>(XoomInitializer.java:38)
	at io.vlingo.xoom.designer.XoomInitializer.main(XoomInitializer.java:87)
	at io.vlingo.xoom.designer.DesignerInitializer.startServer(DesignerInitializer.java:60)
	at io.vlingo.xoom.designer.DesignerInitializer.start(DesignerInitializer.java:32)
	at io.vlingo.xoom.cli.task.designer.DesignerTask.run(DesignerTask.java:30)
	at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.runTask(CommandLineInterfaceInitializer.java:32)
	at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.main(CommandLineInterfaceInitializer.java:26)
Caused by: java.lang.NullPointerException: null
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:506)
	at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:107)
	at io.vlingo.xoom.actors.World.actorFor(World.java:152)
	at io.vlingo.xoom.lattice.grid.GridNode.<init>(GridNode.java:67)
	at io.vlingo.xoom.lattice.grid.GridNodeBootstrap$GridNodeInstantiator.instantiate(GridNodeBootstrap.java:75)
	at io.vlingo.xoom.lattice.grid.GridNodeBootstrap$GridNodeInstantiator.instantiate(GridNodeBootstrap.java:61)
	at io.vlingo.xoom.actors.ActorFactory.actorFor(ActorFactory.java:71)
	at io.vlingo.xoom.actors.Stage.createRawActor(Stage.java:838)
	... 20 common frames omitted`

**Comment by hamzajg** [comment]
Hi, @superfrankiefan, if you are building the xoom-designer locally, you can use these commands to run the .jar file after setting up the `ENV VLINGO_XOOM_DESIGNER_HOME`
```shell
mvn clean package -Pfrontend
java -jar target\xoom-designer-<current-version>-SNAPSHOT.jar gui --target zip-download
```
`gui` argument: to launch the web app gui on the browser
`--target zip-download` argument: to use the zip package feature and generate a zip file

**Comment by superfrankiefan** [comment]
Hi, @hamzajg, I didn't build locally by myself. I downloded the latest designer.zip file, and unzip it. Then run `xoom gui`

**Comment by superfrankiefan** [comment]
Hi @hamzajg, I have tried `./xoom gui --target zip-download` . It works now.
Thanks
