### ISSUE TITLE
Xoom gui fails on start

### ISSUE THREAD

**Issue by niclash** [vlingo/xoom-designer#173]
On Linux Debian "testing" and 
``` bash
$ java -version
openjdk version "21.0.5" 2024-10-15
OpenJDK Runtime Environment (build 21.0.5+11-Debian-1)
OpenJDK 64-Bit Server VM (build 21.0.5+11-Debian-1, mixed mode, sharing)

$ cd temp
$ curl -L -O https://github.com/vlingo/xoom-designer/releases/download/1.9.0/designer.tar
$ tar xf designer.tar
$ mv designer xoom-designer
$ cd xoom-designer/
$ ./xoom-designer/xoom -version
1.8.9-SNAPSHOT
$ ./xoom-designer/xoom gui

service: xoom-designer.

16:39:24.933 [main] ERROR io.vlingo.xoom.actors.Logger - java.lang.NullPointerException: Cannot invoke "io.vlingo.xoom.actors.Stage$ActorProtocolActor.protocolActor()" because "actor" is null
io.vlingo.xoom.designer.DesignerServerInitializationException: java.lang.NullPointerException: Cannot invoke "io.vlingo.xoom.actors.Stage$ActorProtocolActor.protocolActor()" because "actor" is null
        at io.vlingo.xoom.designer.DesignerInitializer.startServer(DesignerInitializer.java:62)
        at io.vlingo.xoom.designer.DesignerInitializer.start(DesignerInitializer.java:32)
        at io.vlingo.xoom.cli.task.designer.DesignerTask.run(DesignerTask.java:30)
        at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.runTask(CommandLineInterfaceInitializer.java:32)
        at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.main(CommandLineInterfaceInitializer.java:26)
Caused by: java.lang.NullPointerException: Cannot invoke "io.vlingo.xoom.actors.Stage$ActorProtocolActor.protocolActor()" because "actor" is null
        at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:470)
        at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:106)
        at io.vlingo.xoom.cluster.model.application.ClusterApplication.instance(ClusterApplication.java:42)
        at io.vlingo.xoom.cluster.model.ClusterSnapshotControl.instance(ClusterSnapshotControl.java:42)
        at io.vlingo.xoom.cluster.model.ClusterSnapshotControl.instance(ClusterSnapshotControl.java:29)
        at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:51)
        at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:37)
        at io.vlingo.xoom.lattice.grid.GridNodeBootstrap.boot(GridNodeBootstrap.java:29)
        at io.vlingo.xoom.lattice.grid.Grid.<init>(Grid.java:98)
        at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:73)
        at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:64)
        at io.vlingo.xoom.turbo.Boot.start(Boot.java:38)
        at io.vlingo.xoom.designer.XoomInitializer.<init>(XoomInitializer.java:37)
        at io.vlingo.xoom.designer.XoomInitializer.main(XoomInitializer.java:85)
        at io.vlingo.xoom.designer.DesignerInitializer.startServer(DesignerInitializer.java:60)
        ... 4 common frames omitted
Exception in thread "main" io.vlingo.xoom.designer.DesignerServerInitializationException: java.lang.NullPointerException: Cannot invoke "io.vlingo.xoom.actors.Stage$ActorProtocolActor.protocolActor()" because "actor" is null
        at io.vlingo.xoom.designer.DesignerInitializer.startServer(DesignerInitializer.java:62)
        at io.vlingo.xoom.designer.DesignerInitializer.start(DesignerInitializer.java:32)
        at io.vlingo.xoom.cli.task.designer.DesignerTask.run(DesignerTask.java:30)
        at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.runTask(CommandLineInterfaceInitializer.java:32)
        at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.main(CommandLineInterfaceInitializer.java:26)
Caused by: java.lang.NullPointerException: Cannot invoke "io.vlingo.xoom.actors.Stage$ActorProtocolActor.protocolActor()" because "actor" is null
        at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:470)
        at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:106)
        at io.vlingo.xoom.cluster.model.application.ClusterApplication.instance(ClusterApplication.java:42)
        at io.vlingo.xoom.cluster.model.ClusterSnapshotControl.instance(ClusterSnapshotControl.java:42)
        at io.vlingo.xoom.cluster.model.ClusterSnapshotControl.instance(ClusterSnapshotControl.java:29)
        at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:51)
        at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:37)
        at io.vlingo.xoom.lattice.grid.GridNodeBootstrap.boot(GridNodeBootstrap.java:29)
        at io.vlingo.xoom.lattice.grid.Grid.<init>(Grid.java:98)
        at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:73)
        at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:64)
        at io.vlingo.xoom.turbo.Boot.start(Boot.java:38)
        at io.vlingo.xoom.designer.XoomInitializer.<init>(XoomInitializer.java:37)
        at io.vlingo.xoom.designer.XoomInitializer.main(XoomInitializer.java:85)
        at io.vlingo.xoom.designer.DesignerInitializer.startServer(DesignerInitializer.java:60)
        ... 4 more
16:39:24.937 [pool-2-thread-7] ERROR io.vlingo.xoom.actors.Logger - Actor instantiation failed because: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @35ef1869
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @35ef1869
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
        at org.nustaq.serialization.FSTClazzInfo.createFieldInfo(FSTClazzInfo.java:512)
        at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:368)
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:129)
        at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
        at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:98)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:85)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:81)
        at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:807)
        at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:477)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:472)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:464)
        at io.vlingo.xoom.lattice.grid.GridNode.<init>(GridNode.java:65)
        at io.vlingo.xoom.lattice.grid.GridNodeBootstrap$GridNodeInstantiator.instantiate(GridNodeBootstrap.java:71)
        at io.vlingo.xoom.lattice.grid.GridNodeBootstrap$GridNodeInstantiator.instantiate(GridNodeBootstrap.java:57)
        at io.vlingo.xoom.actors.ActorFactory.actorFor(ActorFactory.java:71)
        at io.vlingo.xoom.actors.Stage.createRawActor(Stage.java:761)
        at io.vlingo.xoom.actors.Stage.actorProtocolFor(Stage.java:511)
        at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:469)
        at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:106)
        at io.vlingo.xoom.cluster.model.application.ClusterApplication.instance(ClusterApplication.java:42)
        at io.vlingo.xoom.cluster.model.ClusterSnapshotControl.instance(ClusterSnapshotControl.java:42)
        at io.vlingo.xoom.cluster.model.ClusterSnapshotControl.instance(ClusterSnapshotControl.java:29)
        at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:51)
        at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:37)
        at io.vlingo.xoom.lattice.grid.GridNodeBootstrap.boot(GridNodeBootstrap.java:29)
        at io.vlingo.xoom.lattice.grid.Grid.<init>(Grid.java:98)
        at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:73)
        at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:64)
        at io.vlingo.xoom.turbo.Boot.start(Boot.java:38)
        at io.vlingo.xoom.designer.XoomInitializer.<init>(XoomInitializer.java:37)
        at io.vlingo.xoom.designer.XoomInitializer.main(XoomInitializer.java:85)
        at io.vlingo.xoom.designer.DesignerInitializer.startServer(DesignerInitializer.java:60)
        at io.vlingo.xoom.designer.DesignerInitializer.start(DesignerInitializer.java:32)
        at io.vlingo.xoom.cli.task.designer.DesignerTask.run(DesignerTask.java:30)
        at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.runTask(CommandLineInterfaceInitializer.java:32)
        at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.main(CommandLineInterfaceInitializer.java:26)
16:39:24.939 [pool-2-thread-7] ERROR io.vlingo.xoom.actors.Logger - XOOM: FAILED: Actor instantiation failed because: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @35ef1869
java.lang.IllegalArgumentException: Actor instantiation failed because: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @35ef1869
        at io.vlingo.xoom.actors.Stage.createRawActor(Stage.java:764)
        at io.vlingo.xoom.actors.Stage.actorProtocolFor(Stage.java:511)
        at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:469)
        at io.vlingo.xoom.actors.Stage.actorFor(Stage.java:106)
        at io.vlingo.xoom.cluster.model.application.ClusterApplication.instance(ClusterApplication.java:42)
        at io.vlingo.xoom.cluster.model.ClusterSnapshotControl.instance(ClusterSnapshotControl.java:42)
        at io.vlingo.xoom.cluster.model.ClusterSnapshotControl.instance(ClusterSnapshotControl.java:29)
        at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:51)
        at io.vlingo.xoom.cluster.model.Cluster.controlFor(Cluster.java:37)
        at io.vlingo.xoom.lattice.grid.GridNodeBootstrap.boot(GridNodeBootstrap.java:29)
        at io.vlingo.xoom.lattice.grid.Grid.<init>(Grid.java:98)
        at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:73)
        at io.vlingo.xoom.lattice.grid.Grid.start(Grid.java:64)
        at io.vlingo.xoom.turbo.Boot.start(Boot.java:38)
        at io.vlingo.xoom.designer.XoomInitializer.<init>(XoomInitializer.java:37)
        at io.vlingo.xoom.designer.XoomInitializer.main(XoomInitializer.java:85)
        at io.vlingo.xoom.designer.DesignerInitializer.startServer(DesignerInitializer.java:60)
        at io.vlingo.xoom.designer.DesignerInitializer.start(DesignerInitializer.java:32)
        at io.vlingo.xoom.cli.task.designer.DesignerTask.run(DesignerTask.java:30)
        at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.runTask(CommandLineInterfaceInitializer.java:32)
        at io.vlingo.xoom.cli.CommandLineInterfaceInitializer.main(CommandLineInterfaceInitializer.java:26)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @35ef1869
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
        at org.nustaq.serialization.FSTClazzInfo.createFieldInfo(FSTClazzInfo.java:512)
        at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:368)
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:129)
        at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
        at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:98)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:85)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:81)
        at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:807)
        at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:477)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:472)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:464)
        at io.vlingo.xoom.lattice.grid.GridNode.<init>(GridNode.java:65)
        at io.vlingo.xoom.lattice.grid.GridNodeBootstrap$GridNodeInstantiator.instantiate(GridNodeBootstrap.java:71)
        at io.vlingo.xoom.lattice.grid.GridNodeBootstrap$GridNodeInstantiator.instantiate(GridNodeBootstrap.java:57)
        at io.vlingo.xoom.actors.ActorFactory.actorFor(ActorFactory.java:71)
        at io.vlingo.xoom.actors.Stage.createRawActor(Stage.java:761)
        ... 20 common frames omitted

```

**Comment by VaughnVernon** [comment]
Thanks for your feedback, @niclash. We have not been investing in the platform for a while and it's behind in some dependencies. Updating some due to vulnerabilities forces us to also update Svelte and that requires a lot of work. Of course, if there was interest in actual use we would be happy to jump back in. I discussed this with @jakzal, and we agreed that reworking the UI to only use htmx would be best since it would remove major dependencies and ongoing vulnerabilities. For that matter, we could even copy the single htmx file into the repository and life would become so simple. So far neither of us has had time to work on it. BTW, there are a few other platform UIs that need similar work.

**Comment by niclash** [comment]
Ok. I am just browsing out of curiosity, no immediate need for it.

**Comment by VaughnVernon** [comment]
BTW, @niclash, your new hair is amazing.
